name: 💡 Feature request
description: Suggest an idea
labels: [enhancement]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like?
      description: What problem does it solve for you?
    validations:
      required: true
  - type: textarea
    id: notes
    attributes:
      label: Anything else?
      description: Mockups, examples, or how you imagine it working.
